//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamrzone.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ID { get; set; }
        public int Post { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime Expires { get; set; }
    
        public virtual Post Post1 { get; set; }
    }
}
