//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamrzone.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Events = new HashSet<Event>();
            this.Posts1 = new HashSet<Post>();
        }
    
        public int ID { get; set; }
        public int Thread { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public string PContent { get; set; }
        public int Creator { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<bool> IsEvent { get; set; }
        public Nullable<int> ReplyID { get; set; }
        public bool IsLocked { get; set; }
        public byte Permissions { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts1 { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual User User { get; set; }
    }
}
